### ISSUE TITLE
Track filesystem changes

### ISSUE THREAD

**Issue by Salamandar** [chergert/gnome-builder#27]
The file tree does not update when we add/MOVE/remove files from the project. That is… very sad. Hope that is planned :)

**Comment by chergert** [comment]
Difficulty here is that our fulltext index doesn't currently support "removing" items. So we need a way to replace the old item with a "tombstone". Then this should be doable.

**Comment by Salamandar** [comment]
Okay :)
(sorry for the delay ^^)

**Comment by chergert** [comment]
So I think I missed the purpose of this. We do track changes that Builder created, but we do not track changes outside of Builder because of how inotify works on Linux. We'd have to setup an inotify handler for every directory in the project to reliably do that.

At some point we'll get there (because we want to be able to update the search index too), but it is going to take a real balancing act to handle some of the larger project trees we use Builder to hack on (WebKit, Linux kernel, etc).

**Comment by chergert** [comment]
As of 58f14eb7bd2016ade14fbb8fcd419330a529d594 we now support updating the file-search index from file renames (but still only within the application).

I'm going to close this because we use bugzilla.
